
package com.varian.oiscn.anticorruption.osp.authorization.wsdl;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 */
@WebService(name = "IAuthorization", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/")
@XmlSeeAlso({
        ObjectFactory.class
})
public interface IAuthorization {


    /**
     * @param strPrivilegeid
     * @param secToken
     * @return returns com.varian.oiscn.anticorruption.osp.authorization.wsdl.ArrayOfboolean
     * @throws IAuthorizationHasRightsServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "HasRights", action = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/IAuthorization/HasRights")
    @WebResult(name = "HasRightsResult", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/")
    @RequestWrapper(localName = "HasRights", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/", className = "com.varian.oiscn.anticorruption.osp.authorization.wsdl.HasRights")
    @ResponseWrapper(localName = "HasRightsResponse", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/", className = "com.varian.oiscn.anticorruption.osp.authorization.wsdl.HasRightsResponse")
    ArrayOfboolean hasRights(
            @WebParam(name = "secToken", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/")
                    String secToken,
            @WebParam(name = "strPrivilegeid", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/")
                    ArrayOfstring strPrivilegeid)
            throws IAuthorizationHasRightsServiceFaultFaultFaultMessage
    ;

    /**
     * @param secToken
     * @return returns com.varian.oiscn.anticorruption.osp.authorization.wsdl.UserInfo
     * @throws IAuthorizationValidateTokenServiceFaultFaultFaultMessage
     */
    @WebMethod(operationName = "ValidateToken", action = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/IAuthorization/ValidateToken")
    @WebResult(name = "ValidateTokenResult", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/")
    @RequestWrapper(localName = "ValidateToken", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/", className = "com.varian.oiscn.anticorruption.osp.authorization.wsdl.ValidateToken")
    @ResponseWrapper(localName = "ValidateTokenResponse", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/", className = "com.varian.oiscn.anticorruption.osp.authorization.wsdl.ValidateTokenResponse")
    UserInfo validateToken(
            @WebParam(name = "secToken", targetNamespace = "http://schemas.varian.com/Foundation/Platform/Public/Authorization/2011/4/")
                    String secToken)
            throws IAuthorizationValidateTokenServiceFaultFaultFaultMessage
    ;

}
