server:
  type: default
  applicationConnectors:
    - type: http
      port: 55070
  adminConnectors:
    - type: http
      port: 55071
  requestLog:
      type: classic
      appenders:
         - type: file
           currentLogFilename: log/request.log
           threshold: INFO
           archive: true
           maxFileSize: 50000K
           archivedFileCount: 20
           archivedLogFilenamePattern: log/request-%d-%i.log
logging:
  level: INFO
  loggers:
    "com.varian.oiscn":
      level: INFO
      additive: true
      appenders:
        - type: console
          threshold: INFO
        - type: file
          currentLogFilename: log/oiscn.log
          archive: true
          maxFileSize: 50000K
          archivedFileCount: 10
          archivedLogFilenamePattern: log/oiscn-%d-%i.log
  appenders:
    - type: file
      currentLogFilename: log/service.log
      threshold: INFO
      archive: true
      maxFileSize: 50000K
      archivedLogFilenamePattern: log/service-%d-%i.log
      archivedFileCount: 10
      logFormat: " {%n
                      \"logger\":\"%logger\",%n
                      \"timestamp\":\"%d{HH:mm:ss.SSS}\",%n
                      \"level\":\"%level\",%n
                      \"thread\":\"%thread\",%n
                      \"message\":\"%msg\",%n
                      \"throwable\":\"%throwable\"%n
                    },%n"
database:
    driver: com.microsoft.sqlserver.jdbc.SQLServerDriver
    databaseServer: 192.168.48.142
    port: 1433
    database: Qin
    username: 2Ji75KA2qBcJxEkwv3SCeQ==
    password: ohtimGCtpJodmDitPzeBymy3f180rjbRLb+XogHXCoQ=
    maxTotal: 100
    initialSize: 20
    maxIdle: 20
    minIdle: 10
    maxWaitMillis: 5000
    timeBetweenEvictionRunsMillis: 603000
    minEvictableIdleTimeMillis:  1800000
serverAddressOfCCIP: 192.168.48.142
fhirServerBaseUri: http://192.168.48.142:44350
ospAuthenticationWsdlUrl: https://192.168.48.142:55001/OSPServices/Authentication.svc?singleWsdl
ospAuthorizationWsdlUrl: http://192.168.48.142:55000/OSPServices/Authorization.svc?singleWsdl
#ICD-9-CM
diagnosisCodeScheme: ICD-10
stagingCodeScheme: AJCC 7th Ed.
urgentStatusIconDesc: Urgent
alertPatientLabelDesc: Alert
activeStatusIconDesc: Encounter
#keyActivityByCategory
keyActivityType: keyActivityByLane
keyActivityTypeValue: Key Activity
carePathConfigFile: config\CarePath.yaml
callingConfigFile: config\integration\CallingSystem.yaml
permissionConfigFile: config\Permission.yaml
dynamicFormTemplateCategory: CCIP
